import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import { AgoragenticClient, AgoragenticOpenRouterError } from '../openrouter-agent-sdk/src/agoragentic-client.mjs';
function response(status,payload){return new Response(JSON.stringify(payload),{status,headers:{'content-type':'application/json'}})}
test('match constructs an authenticated no-spend preview request',async()=>{let seen;const client=new AgoragenticClient({apiKey:'amk_test_placeholder',fetchImpl:async(url,init)=>{seen={url:String(url),init};return response(200,{providers:[]})}});assert.deepEqual(await client.match({task:'summarize public text',constraints:{max_cost:0}}),{providers:[]});assert.match(seen.url,/\/api\/execute\/match\?/);assert.match(seen.url,/max_cost=0/);assert.equal(seen.init.headers.Authorization,'Bearer amk_test_placeholder')});
test('missing key fails before network',async()=>{let called=false;const client=new AgoragenticClient({apiKey:'',fetchImpl:async()=>{called=true}});await assert.rejects(client.match({task:'x'}),e=>e.code==='missing_api_key');assert.equal(called,false)});
test('HTTP errors preserve retryability',async()=>{const client=new AgoragenticClient({apiKey:'amk_test_placeholder',fetchImpl:async()=>response(429,{error:{code:'rate_limited',message:'slow down'}})});await assert.rejects(client.quote({task:'x'}),e=>e instanceof AgoragenticOpenRouterError&&e.retryable&&e.status===429)});
test('execute tool is approval-gated and safe example exposes match only',async()=>{const tools=await readFile(new URL('../openrouter-agent-sdk/src/agoragentic-tools.mjs',import.meta.url),'utf8');assert.match(tools,/name:\s*'agoragentic_execute'[\s\S]*?requireApproval:\s*true/);const example=await readFile(new URL('../openrouter-agent-sdk/examples/match-only.mjs',import.meta.url),'utf8');assert.match(example,/tools:\s*\[match\]/);assert.doesNotMatch(example,/tools:\s*\[[^\]]*execute/)});
test('Codebuff candidate deliberately omits execute',async()=>{const source=await readFile(new URL('../adapters/codebuff-tools.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/toolName:\s*'agoragentic_execute'/)});
test('Oration creation has dual gate plus telephony and DND gates',async()=>{const source=await readFile(new URL('../adapters/oration-client.mjs',import.meta.url),'utf8');for(const required of ['ORATION_ENABLE_CREATE','ownerApproved','ORATION_ENABLE_TELEPHONY','ORATION_ALLOW_IGNORE_DND']) assert.ok(source.includes(required))});
